name: 'Build images with Packer'
author: 'Chad Pritchett <chad.pritchett@rackspace.com>'
description: 'Build virtual-machine images using Packer'

inputs:
  only:
    description: 'Run only the specified Virtual-Machine builders'
    required: false
  options:
    description: 'Optional command arguments to be provided when calling Packer'
    required: false
  secret:
    description: 'The secret will be written to /tmp/packer-secret, see Providing Secrets'
    required: false
  template:
    description: 'Source file that defines how machine images are built'
    required: true
    default: 'default.json'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'archive'
  color: 'blue'
